### ISSUE TITLE
New Feuture - change alert messege and buttons text 

### ISSUE THREAD

**Issue by brunoda6** [huitingyeong/bluetooth_enable#1]
Hi this not an issue,

I just wondering if you can give the ability to pass a message,btnTextSuccess,btnTextDenied params to change the texts.

Other than that the package is awsome thanks :)

**Comment by huitingyeong** [comment]
Hi i'll see what I can do but it may take sometime

**Comment by brunoda6** [comment]
No problem thanks

**Comment by huitingyeong** [comment]
I have committed the changes for new feature. Will be closing this issue
